//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIFv2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public short Banco_Id { get; set; }
        public string Cuenta_Id { get; set; }
        public short Tipo_Cuenta_Banco_Id { get; set; }
        public string Cuenta_Dsc { get; set; }
        public string Cuenta_ABA { get; set; }
        public string Cuenta_Responsable { get; set; }
        public short Divisa_Id { get; set; }
        public string Cuenta_Sucursal { get; set; }
        public string Cuenta_Localidad { get; set; }
        public short Pais_Id { get; set; }
        public string Cuenta_Gerente { get; set; }
        public string Cuenta_Telefono { get; set; }
        public string Cuenta_Fax { get; set; }
        public string Cuenta_Email { get; set; }
        public string Cuenta_Ejecutivo { get; set; }
        public string Cuenta_Tel_Ejecutivo { get; set; }
        public string Cuenta_Fax_Ejecutivo { get; set; }
        public string Cuenta_Email_Ejecutivo { get; set; }
        public string Cuenta_Ref_1 { get; set; }
        public string Cuenta_Ref_2 { get; set; }
        public string Cuenta_Ref_3 { get; set; }
        public string Cuenta_Ref_4 { get; set; }
        public string Cuenta_Ref_Valor_1 { get; set; }
        public string Cuenta_Ref_Valor_2 { get; set; }
        public string Cuenta_Ref_Valor_3 { get; set; }
        public string Cuenta_Ref_Valor_4 { get; set; }
        public string Cuenta_Clave_1 { get; set; }
        public string Cuenta_Clave_2 { get; set; }
        public string Cuenta_Clave_3 { get; set; }
        public string Cuenta_Clave_4 { get; set; }
        public string Cuenta_Clave_Valor_1 { get; set; }
        public string Cuenta_Clave_Valor_2 { get; set; }
        public string Cuenta_Clave_Valor_3 { get; set; }
        public string Cuenta_Clave_Valor_4 { get; set; }
        public double Cuenta_SaldoIni_Anio { get; set; }
        public double Cuenta_Ingreso_Anio { get; set; }
        public double Cuenta_Egreso_Anio { get; set; }
        public double Cuenta_SaldoIni_Mes { get; set; }
        public double Cuenta_Ingreso_Mes { get; set; }
        public double Cuenta_Egreso_Mes { get; set; }
        public double Cuenta_SaldoIni_Dia { get; set; }
        public double Cuenta_Ingreso_Dia { get; set; }
        public double Cuenta_Egreso_Dia { get; set; }
        public string Cuenta_Plaza { get; set; }
        public bool Cuenta_Considera_Plaza { get; set; }
        public short Tipo_Cuenta_Id { get; set; }
        public short Sts_Cuenta_Id { get; set; }
        public bool Cuenta_Emite_Cheques { get; set; }
        public byte Cuenta_Prioridad { get; set; }
        public string Cuenta_Cuenta_Contable { get; set; }
        public byte[] Integridad { get; set; }
        public string Cuenta_Responsable_Email { get; set; }
    
        public virtual Banco Banco { get; set; }
    }
}
