//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIFv2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Divisa
    {
        public short Divisa_Id { get; set; }
        public string Divisa_Dsc { get; set; }
        public string Divisa_Dsc_Corta { get; set; }
    }
}
