//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIFv2Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SPEIEntities : DbContext
    {
        public SPEIEntities()
            : base("name=SPEIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<Divisa> Divisa { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<sp_s_Bancos_Result> sp_s_Bancos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_s_Bancos_Result>("sp_s_Bancos");
        }
    }
}
