//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIIFv2Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Usuario_Id { get; set; }
        public short Nivel_Id { get; set; }
        public string Usuario_Dsc { get; set; }
        public string Usuario_Password { get; set; }
        public System.DateTime Usuario_Fecha_Pwd { get; set; }
        public string Usuario_Area { get; set; }
        public string Usuario_Puesto { get; set; }
        public System.DateTime Usuario_Fecha_UltAcceso { get; set; }
        public bool Usuario_Inactivo { get; set; }
        public byte Usuario_No_Intentos { get; set; }
        public string Usuario_Id_Windows { get; set; }
        public short Sucursal_Id { get; set; }
    
        public virtual Nivel Nivel { get; set; }
    }
}
